services:
  php:
    build:
      context: .
      dockerfile: ./devops/docker/Dockerfile
    environment:
      - RPC_USER=solodev
      - RPC_PASSWORD=password
      - RPC_PORT=22555
      - RPC_IP=54.236.88.9
      - CHAIN_SYMBOL=DOGE
    ports:
      - 9000
    volumes:
      - ./data:/var/www/data
      - ./views:/var/www/views
      - ./src:/var/www/src
      - ./public:/var/www/html

  proxy: 
    build:
      context: .
      dockerfile: ./devops/docker/Dockerfile.ui
    environment:
      APP_ENV: ${APP_ENV}
      APP_URL: php:9000
    ports:
      - '${HTTP_PORT}:80'
      - '${HTTPS_PORT}:443'
    volumes:
      - ./public:/var/www/html
    links:
      - php
    depends_on:
      - php
    restart: always