<footer>
<div class="pull-right">
<img width="25px" src="assets/images/coin.png"> <?= CHAIN_SYMBOL ?> Node Manager - © 2017 - 2025
</div>
<div class="clearfix"></div>
</footer>
<script type="text/javascript">
	<?php
	if($this->section === "main"){
		$section = "";
	}else{
		$section = "?p=".$this->section;
	}
	?>
	window.history.pushState("", "", "<?= $section ?>");

  const openMobileMenu = () => {
    const x = document.getElementById("mobileLinks");
    if (x.style.display === "block") {
      x.style.display = "none";
    } else {
      x.style.display = "block";
    }
}
</script>
